---
sections:
  - label: Blog Posts
    name: posts
    path: content/posts
    templates:
      - article
    type: directory
    create: documents
    match: '**/*.md'
    new_doc_ext: md
  - label: Authors
    name: authors
    path: content/authors
    templates:
      - author
    type: directory
    create: documents
    match: '**/*.md'
    new_doc_ext: md
  - label: Cover
    name: cover
    path: content/cover
    templates:
      - CoverPage
    type: directory
    create: documents
    match: '**/*.md'
    new_doc_ext: md
